# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/.local/bin:$HOME/bin

export PATH

# Use make -j$numcores by default
HOSTCPUS="$(grep -c ^processor /proc/cpuinfo)"
export MAKEFLAGS="-j$(expr $HOSTCPUS \* 2)"
