# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

if [ -e /usr/share/git-core/contrib/completion/git-prompt.sh ] ; then
    source /usr/share/git-core/contrib/completion/git-prompt.sh
fi

if type -t __git_ps1 | grep -q function ; then
    export PS1='[\u@\h \W$(__git_ps1 " (%s)")]\$ '
    export GIT_PS1_SHOWDIRTYSTATE=1
fi

# User specific aliases and functions

export EDITOR="vim"
export VISUAL="vim"
export EMAIL="Anya Harter <aharter@redhat.com>"
if ! echo "$PATH" | grep -q $HOME; then
    export PATH="$PATH:$HOME/bin"
fi
